### PR TITLE
Make use of the argparse libary

### PR DESCRIPTION
**Pull request by immanenz**
Python has a great [libary](https://docs.python.org/3.4/library/argparse.html#module-argparse) for parsing command line arguments.
The [print_help()](https://docs.python.org/3.4/library/argparse.html#argparse.ArgumentParser.print_help) function is pretty handy for generating a help message.

Furthermore:
- Remove unused `usage()` function
- Remove unused `checkquery()` function
- Code cleanup

### CODE REVIEW

**Comment by QuadPiece** [comment]
May I ask if this code is tested. I don't have the ability to test it currently

**Comment by llyyr** [comment]
I had believed that argparse is not a built in library. I guess I was wrong then.

Also I tested the code and it works with Python 3+. You could just edit the imports a bit to make it work on Python 2.7+.

**Comment by QuadPiece** [comment]
I'll merge this, then look into Python 2.7 support later.

**Comment by immanenz** [comment]
Yes, I tested my code. Thanks for merging.

**Pull request merged**
